language: node_js

node_js:
  - "4.0"
  - "5.0"
  - "6.0"

branches:
  only:
    - master

notifications:
  email:
    on_success: change
    on_failure: always

script:
  - npm run -s lint
  - npm run -s test
  - npm run -s update-coverage

addons:
    code_climate:
        repo_token: 5ff4e439344b8981c89c0fd22dd7481696bb84270969871b9bec03494bb74c39
